model:
  name: "google/gemma-2-27b-it"
  base_url: "https://api.together.xyz/v1"
  temperature: 0.7
  max_tokens: 2000

aperturedb:
  tools:
    - name: "search_similar_companies"
      description: "Search for similar companies in the database based on description"
      function:
        name: "search_similar_companies"
        description: "Find similar companies based on text description"
        parameters:
          type: "object"
          properties:
            description:
              type: "string"
              description: "Company or product description to search for"
            limit:
              type: "integer"
              description: "Maximum number of results to return"
              default: 5

    - name: "search_market_data"
      description: "Search for market data and trends in the database"
      function:
        name: "search_market_data"
        description: "Find market data and trends based on keywords"
        parameters:
          type: "object"
          properties:
            keywords:
              type: "string"
              description: "Keywords to search for in market data"
            limit:
              type: "integer"
              description: "Maximum number of results to return"
              default: 5

prompts:
  system: |
    You are a founder-minded AI assistant specialized in identifying business opportunities and trends.
    Think like a founder looking for fast-growing business opportunities and a venture investor evaluating YC acceptance chances.
    Your analysis should be data-driven, focusing on growth potential, market dynamics, and unique value propositions.
    You will perform analysis in multiple steps, each building upon the previous step's findings.
    You have access to a database of market data and company information through ApertureDB.

  trend_analysis: |
    Think as a founder looking for a fast growing business opportunity in the following area:
    {user_input}

    Task:
    1. Identify trends that would shape the forecasting area within the 5 year time horizon (2025-2030).
    2. Consider these trend types:
       - Market forces affecting the area (positive/negative growth rate)
       - Enabling technologies making things faster/cheaper/better (positive/negative adoption rate)
       - Social format changes in stakeholder behavior (positive/negative adoption rate)
    3. Visualize each trend according to five phases of Gartner hype cycle
    4. Choose EXACTLY {k} most influential trends by compounding growth rate by 2030
    5. For each trend, identify startup opportunities that:
       - Intersect with at least one other trend
       - Can arise as trend consequences (like diners/motels arising from automobile development)
       - Can achieve >5% week-over-week growth
       - Are unique (cosine similarity <0.85 with existing market solutions)
    6. Evaluate YC acceptance chances for each opportunity

    Requirements for each trend:
    - Name (under 50 chars)
    - Description (under 100 chars)
    - Growth projections for 2025-2030 (as positive integer percentages, e.g., 65 means 65%)
    - Startup opportunity description (under 100 chars)
    - Week-over-week growth rate (as decimal between 0 and 1)
    - YC acceptance probability (as decimal between 0 and 1)
    - Related trends (comma separated)

    Response must follow this exact format:
    {format_instructions}

  opportunity_analysis: |
    Based on the following trend analysis:
    {trend_analysis}

    Analyze potential business opportunities for:
    {user_input}

    Focus on:
    1. Market size and growth potential
    2. Revenue models and monetization strategies
    3. Target customer segments
    4. Unique value propositions (ensure cosine similarity <0.85 with existing solutions)
    5. Initial go-to-market strategy
    6. Intersection points with multiple trends
    7. Expected week-over-week growth rate
    8. YC acceptance probability

    Format your response as a clear, structured analysis.

  competitor_analysis: |
    Based on the following opportunity analysis:
    {opportunity_analysis}

    Analyze the competitive landscape for:
    {user_input}

    Focus on:
    1. Direct and indirect competitors
    2. Uniqueness validation (cosine similarity check)
    3. Market positioning
    4. Barriers to entry
    5. Competitive advantages from trend intersections
    6. Growth rate validation

    Format your response as a clear, structured analysis.

  bi_report: |
    Based on the following analyses:
    
    Trend Analysis:
    {trend_analysis}
    
    Opportunity Analysis:
    {opportunity_analysis}
    
    Competitor Analysis:
    {competitor_analysis}

    Provide a comprehensive analysis for:
    {user_input}

    Include:
    1. Most promising trends and their growth trajectories
    2. Key opportunities and their potential impact
    3. Competitive landscape and market dynamics
    4. Recommended strategies and next steps

    Format your response as a clear, structured analysis.

  user_template: |
    Analyze the following business context with focus on {focus_area}:
    {user_input}

api:
  host: "0.0.0.0"
  port: 8000
  title: "SpyGlass API"
  description: "API for analyzing business opportunities and trends"
  version: "1.0.0"
